weather_task
asifnaseebi/weather_task pull request #1
Opened 2023-03-07 18:20 UTC by asifnaseebi

2023-03-08 07:46 UTC, Hamma111 requested changes

2023-03-08 07:46 UTC, Hamma111 commented on 7_march.py
> +import os
what does this file do?

2023-03-08 07:46 UTC, Hamma111 commented on main.py
> +import os
are we using this file? if not, why is this in the pull request?

2023-03-08 07:46 UTC, Hamma111 commented on weather.py
> +min_temp_year = min(temperatures, key=temperatures.get)
what is `temperatures.get`?

2023-03-08 07:46 UTC, Hamma111 commented on weather.py
> +max_temp_year = max(temperatures, key=temperatures.get)
what does `min()` and `max()` function do in python. 

what does the `key`argument do in min or max function?

2023-03-08 09:24 UTC, asifnaseebi commented on weather.py
> +max_temp_year = max(temperatures, key=temperatures.get)
min() یہ سب سے ہڑے چھوٹے نمبر کو  پکڑنے کیلءے استعمال ہوتا ہے
mix() اور یہ بڑے نمبر کیلءے

2023-04-11 19:07 UTC, merged

2023-04-12 09:03 UTC, Hamma111 commented on weather.py
> +max_temp_year = max(temperatures, key=temperatures.get)
try to use english :p just saw it today

2023-04-12 10:09 UTC, asifnaseebi commented on weather.py
> +max_temp_year = max(temperatures, key=temperatures.get)
ok inshaAllah